default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: simplecritic
  password: password1

development:
  <<: *default
  database: simplecritic_development

test:
  <<: *default
  database: simplecritic_test
