default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: zach
  password: <%= ENV['RAILS_DEV_PASSWORD'] %>

development:
  <<: *default
  database: postgres_dev

test:
  <<: *default
  database: postgres_test
  